# Generated by Django 3.0.8 on 2020-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20200829_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
    ]
