# Generated by Django 3.0.8 on 2020-08-30 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.CharField(max_length=15)),
                ('dkey', models.CharField(max_length=15)),
                ('category', models.TextField()),
                ('content', models.TextField()),
                ('stime', models.TimeField(default=datetime.datetime.now)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('etime', models.TimeField(default=datetime.datetime.now)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
