# Generated by Django 3.0.8 on 2020-08-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='category',
        ),
    ]
